title: jekyll-leaflet
description: >- # this means to ignore newlines until "baseurl:"
  Create leaflet.js maps in Jekyll
markdown: kramdown
baseurl: /tech/jekyll-leaflet/
theme: minima
plugins:
    - jekyll-leaflet
